version: '2'
services:
 mongo:
   image: mongo
   ports:
     - "27018:27017"
   command: "--smallfiles --logpath=/dev/null"
   mem_limit: 2G
   mem_reservation: 2G
   memswap_limit: 2G
   cpuset: '0'
   cpus: 1

 app:
   build: .
   stdin_open: true
   mem_limit: 2G
   mem_reservation: 2G
   memswap_limit: 2G
   cpus: 2
   cpu_quota: 100000
   ports:
     - "3001:3001"
   links:
     - mongo
   environment:
     MONGO_URL: 'mongodb://mongo/projects'
